-- ============================================
-- Supabase Schema for EduAttend
-- Jalankan di SQL Editor Supabase
-- ============================================

-- Classes
create table classes (
  id bigint generated by default as identity primary key,
  name text not null,
  wa_group_link text,
  created_at timestamptz default now() not null
);

-- Students
create table students (
  id bigint generated by default as identity primary key,
  name text not null,
  nisn text not null unique,
  class_id bigint references classes(id) on delete cascade,
  created_at timestamptz default now() not null
);

-- Attendance
create table attendance (
  id bigint generated by default as identity primary key,
  student_id bigint references students(id) on delete cascade,
  class_id bigint references classes(id) on delete cascade,
  date date not null,
  status text not null default 'H',
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  unique (student_id, date)
);

-- Indexes
create index idx_students_class_id on students(class_id);
create index idx_attendance_class_id on attendance(class_id);
create index idx_attendance_student_id on attendance(student_id);
create index idx_attendance_date on attendance(date);

-- Data contoh (opsional)
-- insert into classes (name, wa_group_link) values ('XII MIPA 1', 'https://chat.whatsapp.com/example');
